del "temporary data.json"
del "Recently Played Summoners in Friend List.xlsx"
del "Recently Played Summoners in Friend Requests.xlsx"
del "Recently Played Summoners in Specified Player List.xlsx"
del /s "Recently Played Summoners *.xlsx"
del /s "*.pkl"
del "GameTypeConfig.json"
del "Perks.xlsx"
del "Recommended Page.json"
del "MyPage.json"
del "Player Stats in Match *.xlsx"
