del "temporary data.json"
del "Recently Played Summoners in Friend List.xlsx"
del "Recently Played Summoners in Friend Requests.xlsx"
del "Recently Played Summoners in Specified Player List.xlsx"
del /s "Recently Played Summoners *.xlsx"
del /s "*.pkl"